/**
 * Critical Challenge chrome selectors that must remain styled in arena.css.
 * Used by CSS contract regression tests.
 */
export const CHALLENGE_CHROME_SELECTORS = [
  '.arena-root.is-playing.is-challenge-fit',
  '.arena-board-stage',
  '.arena-board-pan',
  '.arena-chrome-layer',
  '.arena-topbar',
  '.arena-opponent-rail',
  '.life-orb',
  '.arena-battlefield',
  '.bf-half-opponent',
  '.bf-half-player',
  '.bf-half-divider',
  '.player-phase-mark',
  '.player-life-stack',
  '.player-dock',
  '.hand-dock',
  '.arena-play-actions',
  '.arena-primary-action',
  '.arena-secondary-action',
  '.arena-action-hint',
  '.mana-pool-hud',
  '.land-stack',
  '.bf-creatures.is-dense',
  '.bf-creatures.is-crowded',
  '.bf-lands.is-dense',
  '.bf-lands.is-crowded',
  /* Footprint contracts: crowded overlap uses the same rule family for cards + stacks */
  '.bf-creatures.is-crowded > .arena-card.is-board',
  '.bf-lands.is-crowded > .arena-card.is-board',
  '.bf-lands.is-crowded > .land-stack',
  '.hand-card.is-playable',
  '.settlement-panel',
  '.arena-setup',
  '.setup-section-title',
  '.setup-section-meta',
  '.setup-hero-grid',
  '.setup-deck-grid',
  '.setup-cta-row',
] as const
