/**
 * Local static asset ↔ remote CDN lookup.
 * JSON is generated by `npm run generate:card-image-map` — do not hand-edit.
 */
import mapJson from './cardImageMap.json'

export type CardImageKind =
  | 'small'
  | 'normal'
  | 'large'
  | 'art_crop'
  | 'card_back'
  | 'cover'
  | 'mana_symbol'

export type CardImageSource =
  | 'challenge'
  | 'player'
  | 'heroes'
  | 'deck_back'
  | 'classic_back'
  | 'cover'
  | 'mana'

export interface CardImageMapEntry {
  id: string
  kind: CardImageKind
  local: string
  remote: string
  source: CardImageSource
}

interface CardImageMapFile {
  generatedAt: string
  classicCardBackId: string
  entries: CardImageMapEntry[]
}

const data = mapJson as CardImageMapFile

const byLocal = new Map<string, CardImageMapEntry>()
const byIdKind = new Map<string, CardImageMapEntry>()

for (const entry of data.entries) {
  byLocal.set(normalizeLocalPath(entry.local), entry)
  byIdKind.set(`${entry.id.toLowerCase()}::${entry.kind}`, entry)
}

export function normalizeLocalPath(path: string): string {
  return path.replace(/^\//, '').replace(/\\/g, '/')
}

export function getClassicCardBackId(): string {
  return data.classicCardBackId
}

export function listMappedCardImages(): readonly CardImageMapEntry[] {
  return data.entries
}

export function lookupByLocalPath(
  localPath: string | null | undefined,
): CardImageMapEntry | undefined {
  if (!localPath) return undefined
  if (/^https?:\/\//i.test(localPath)) return undefined
  return byLocal.get(normalizeLocalPath(localPath))
}

export function lookupByCardId(
  id: string | null | undefined,
  kind: CardImageKind,
): CardImageMapEntry | undefined {
  if (!id) return undefined
  return byIdKind.get(`${id.toLowerCase()}::${kind}`)
}
